#!/usr/bin/env bash
#
# Alias for gradlew.  Used for development.  It starts
# the gradle daemon which should only be used
# when developing.
#
# Example:  ./gw clean build -x test
#
# Make script executable: chmod +x gw
#

export LOGGING_CONFIG=classpath:log4j2-local.xml

./gradlew $@