#!/bin/bash
#
# Creates a database named iat on the local Postgres instance
#
# Two users are created : iat_admin and iat
#
# Password is a required argument when running the script
#

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Creating database 'iat' failed.  You must provide password for user."
  echo "Usage: $0 {password}"
  exit $E_BADARGS
fi


psql -U postgres << END_OF_SCRIPT

CREATE ROLE "iat_admin" with LOGIN CREATEDB CREATEROLE PASSWORD '$1';

END_OF_SCRIPT

psql -U iat_admin postgres << END_OF_SCRIPT

CREATE DATABASE "iat";

END_OF_SCRIPT

psql -U postgres << END_OF_SCRIPT

CREATE ROLE iat LOGIN PASSWORD '$1';

GRANT CONNECT ON DATABASE iat TO iat;

GRANT ALL ON ALL TABLES IN SCHEMA public TO iat_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO iat;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO iat_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO iat;

ALTER DEFAULT PRIVILEGES
    FOR ROLE iat_admin
    IN SCHEMA public
    GRANT ALL ON TABLES TO iat_admin;

ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO iat;

ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO iat_admin;

ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO iat;

END_OF_SCRIPT
